Day3
susird/30DaysOfJavaScript pull request #3
Opened 2021-04-13 03:10 UTC by susird

This is finally the pr of 3th day for 30 Days of JavaScript :sparkle: :sparkles:

2021-04-14 01:06 UTC, josepplloo reviewed
nice work! 
We need to make a deep review of the concepts, you will start to understand more and more when you face more challenges don't worry, the beginning is always overwhelming

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +console.log(parseInt('9.8') == 10)
always try to check for type, so use `===`

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +console.log('potato' != 'minino')
`'potato' !== 'minino'`

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +//9. Writ a script that prompt a user to enter hours and rate per hour. Calculate pay of the person?
Write

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +  let base = prompt('Insert base here',);
why `let` ?

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +  if (yourName.length > familyName.length) {
what happen if `yourName.length === familyName.length` ?

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +  let birthYear = prompt('Enter number of yours you live',);
let age= prompt(Enter your age');

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +  let calculate = birthYear * seccondsYear;
calculateSecondsLeft = 100 * seccondsYear - age * seccondsYear;

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +}
why did you not use a function to make this?

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +function twoDigitsMin() {
those are the same function:
``` 
const formatTwoDigits = (numberToFormat) => numberToFormat < 10 ? `0${numberToFormat}` : String(numberToFormat);
const dateMinutes = now.getMinutes()
const dateHours = now.getHours();
formatTwoDigits(dateMinutes);
formatTwoDigits(dateHours);
```

2021-04-14 01:06 UTC, josepplloo commented on Day3/index.html
> +</html>
Insert new line

2021-04-14 01:06 UTC, josepplloo commented on Day3/excercises_day3.js
> +console.log(`${dateYear}-${dateMonth}-${dateDay}` + " " + twoDigitsHour() + ":" + twoDigitsMin())
insert New line

2021-04-15 20:35 UTC, susird commented on Day3/excercises_day3.js
> +  let calculate = birthYear * seccondsYear;
Change birthYear

2021-04-17 18:34 UTC, josepplloo requested changes
Fix all the code styles problem and youse would merge this PR! 🥇

2021-04-17 18:34 UTC, josepplloo commented on Day3/excercises_day3.js
> +let firstName = 'Susana'
why not `const`?

2021-04-17 18:34 UTC, josepplloo commented on Day3/excercises_day3.js
> +  let area = ((0.5) * base * height);
const

2021-04-17 18:34 UTC, josepplloo commented on Day3/excercises_day3.js
> +  let x = prompt('Insert the intercept here',);
idem

2021-04-17 18:34 UTC, josepplloo commented on Day3/excercises_day3.js
> +  const rate = prompt(`Insert rate per hour here`,);
no trailing comma

2021-04-17 18:34 UTC, josepplloo commented on Day3/excercises_day3.js
> +  const rate = prompt(`Insert rate per hour here`,);
if  `  necessary here?

2021-04-17 18:34 UTC, josepplloo commented on Day3/excercises_day3.js
> +//12. Declare two variables myAge and yourAge and assign them initial values and myAge and yourAge.
what a weird problem 😖

2021-04-17 18:34 UTC, josepplloo commented on Day3/index.html
> +</html>
your need to insert an empty line to the end of the files to avoid compilation problems

2021-04-19 19:56 UTC, josepplloo requested changes
Only a few comments, 💅

2021-04-19 19:56 UTC, josepplloo commented on Day3/excercises_day3.js
> +console.log(`${dateYear}-${dateMonth}-${dateDay}` + " " + twoDigitsHour() + ":" + twoDigitsHour())
twoDigitsHour do not return anything 🤷

2021-04-19 19:56 UTC, josepplloo commented on Day3/excercises_day3.js
> +    alert(`Your name is short`);
` -> '

2021-04-19 19:56 UTC, josepplloo commented on Day3/excercises_day3.js
> +  const circRadius = prompt('Insert radius here');
change the name to `radius`, and try not to use abbreviations. 
only in special cases eg https://www.acronymfinder.com/Circumference-(CIRCUM).html

2021-04-19 20:41 UTC, anyruizd commented on Day3/excercises_day3.js
> +//console.log(driveAge())
do you need this here?

2021-04-19 20:41 UTC, anyruizd commented on Day3/excercises_day3.js
> +//console.log(slopeCalculate >= calcSlope)
what about this here? and the spaces below?

2021-04-19 20:41 UTC, anyruizd commented on Day3/excercises_day3.js
> +    alert(`Your name is short`);
@susird you don't need to use ` here, use ' instead.

2021-04-20 15:09 UTC, anyruizd commented on Day3/excercises_day3.js
> +  let y = ((2 * x) - 2);
Don't see any reason for you to be using `let` here.

2021-04-21 19:23 UTC, anyruizd approved these changes

2021-04-21 19:23 UTC, josepplloo approved these changes
🥇

2021-04-21 19:26 UTC, merged