Day4
susird/30DaysOfJavaScript pull request #4
Opened 2021-04-15 23:07 UTC by susird

This is the Pr of 4th day of 30 Days of JavaScript challenge :space_invader: :sparkles:

2021-04-16 03:19 UTC, anyruizd requested changes
Let's change all the switches for if/else. A lot of people in this industry consider using switch as a bad practice, and while it's important to learn how to use it, you need to learn how to use the most used conditionals: if/else.

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +  let underAge = (18 - oldUser);
why are you using `let`?

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +console.log(ageUser())
If the rest of the code has semicolons, please be consistent and add them to this piece of code.

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +  let meOlderThan = myAge - yourAge;
`let`?

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +console.log(compareAges())
so half of your code has semicolons and these lines don't.

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +//console.log(compare)
Do you need these lines?

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +    //alert(`Your grade is F'`);
So this line is not working? Is it needed?

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +    alert(`Your grade is A'`);
Hm, I don't think this is the desired behavior for the default case. Because if the student doesn't have a grade, it will get an A?

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +}
Since you didn't give us context about what this exercise is about, I'm not sure if this is expected or not. But I might ask: do you think this is an appropriate solution for a programmer? Do you think programming is about repeating all these lines of code that are so similar? Wasn't that cumbersome of writing?

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +typeOfDay()
consistency with the use of semicolons

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +}
why use a switch when you can use an if/else? 
And besides, it doesn't make sense to ask for `switch(true)` it will always be true!

2021-04-16 03:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +}
This switch doesn't make sense.

2021-04-16 04:48 UTC, anyruizd commented on index.html
>  </html>
Since you're not rendering anything in the web page, you don't need this HTML file. Just run your js file in your terminal running `node name-of-the-file.js` and it should work the same as in the web console.

2021-04-21 21:19 UTC, anyruizd commented on Day4/4dayExcercises.js
> +    alert(`You are old enough to drive.`);
Remember: ⚠️ if you're not interpolating variables, you don't need to use back ticks (`)

2021-04-21 21:23 UTC, anyruizd commented on Day4/4dayExcercises.js
> +}
Please move the calculation that is inside the ifs, to a separate variable to make it more readable for all the seasons.

```
const isAutumn = monthSeason === 'september' || monthSeason === 'october' || monthSeason === 'november'

if(isAutumn) { ... } 
```

2021-04-21 23:54 UTC, anyruizd reviewed
New changes to improve readability 😀

2021-04-21 23:54 UTC, anyruizd commented on Day4/4dayExcercises.js
> +  if (number % 2 == 0) {
Same here with the calculation inside the if, it could be 
```
  const isEven = number % 2 == 0;
  if (isEven) {...}
```

2021-04-21 23:54 UTC, anyruizd commented on Day4/4dayExcercises.js
> +if (month === 'november' || month === 'april' || month === 'june' || month === 'september') {
Same here with the calculations inside the id.

2021-04-21 23:54 UTC, anyruizd commented on Day4/4dayExcercises.js
> +if (monthOfYear === 'november' || monthOfYear === 'april' || monthOfYear === 'june' || monthOfYear === 'september') {
Same

2021-04-22 21:08 UTC, anyruizd commented on Day4/4dayExcercises.js
> +    alert('You are left with ${underAge} years to drive.')
🤔 I think this is not working properly, the first alert didn't need the backticks because it wasn't interpolating any variable, but the second one does need it because is interpolating the `underAge` variable.

2021-04-22 21:09 UTC, josepplloo approved these changes
Only a few comments, Nice Job! 🚀

2021-04-22 21:09 UTC, josepplloo commented on Day4/4dayExcercises.js
> +0
what this 0 is here?

2021-04-22 21:09 UTC, josepplloo commented on Day4/4dayExcercises.js
> +
delete those lines

2021-04-22 21:09 UTC, anyruizd commented on Day4/4dayExcercises.js
> +const daysInAMonth = month === 'november' || month === 'april' || month === 'june' || month === 'september';
Maybe a better name for this could be `hasThirtyDays`

2021-04-22 21:12 UTC, anyruizd commented on Day4/4dayExcercises.js
> +const month = monthOfYear === 'november' || monthOfYear === 'april' || monthOfYear === 'june' || monthOfYear === 'september';
same here, a better name would be `hasThirtyDays`

2021-04-22 21:23 UTC, anyruizd approved these changes
LGTM 👍🏽

2021-04-22 21:33 UTC, merged