Day5 "Arrays" Of 30 Days of Javascript
susird/30DaysOfJavaScript pull request #5
Opened 2021-05-06 22:15 UTC by susird

This is the pull request "Arrays" of 30 days of javascript :sparkle:

2021-05-07 22:17 UTC, susird commented on Day5/fifthDayExcercises.js
> +  const isEthiopia = countries.indexOf(country) !== -1;
better: const hasEthiopia

2021-05-07 22:23 UTC, susird commented on Day5/fifthDayExcercises.js
> +//const ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
Do you need this commented?

2021-05-08 20:58 UTC, anyruizd requested changes

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +let itCompanies = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'];
???

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(itCompanies.splice());
Please, avoid doing all this logic inside the console.log statement, instead assign the result of the logic to a variable and console.log the variable.

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +let words = text.replace(/[.,]/g, "").split(' ');
???

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +function findingCountry(countries = [], country = '') {
Since `finding` is not the verb's infinitive form, this is not a proper name for the function and because it doesn't imply an action. Please, update it.

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +  const hasSass = webTech.indexOf(tech) !== -1;
Yo tried to name the function and variables in a general way, so it is not linked to a particular technology, which is good. But then, you named this variable as the particular tech 🤷🏽, please change the name to a better one.

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const sortedArray = ages.sort((a, b) => a - b);
Wouldn't it be better to name it `sortedAges`?

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const half = sortedArray.length / 2;
half of what?

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const reducer = (accumulator, currentValue) => accumulator + currentValue;
Do you think you can find a better name for `reducer`?

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const average = ages.reduce(reducer) / ages.length;
average what?

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +  //Compare the value of (min - average) and (max - average), use abs() method
why the indentation here?

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const comparition = Math.abs(maxLessAverage === minLessAverage);
It doesn't make sense to use `abs` in a boolean value. This method should be used in the calculations instead.

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(countries.slice(0, 10));
Don't do the logic inside the console.log statement.

2021-05-08 20:58 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(secondHalfCountries);
You're only considering one of the cases requested in the exercise. I don't see you're using an if to check if the countries array is even or odd. This exercise is incomplete.

2021-05-08 20:58 UTC, anyruizd commented on Day5/web_techs.js
> +module.exports = webTechs
????

2021-05-11 02:47 UTC, josepplloo reviewed
:D only some issues with the variable names

2021-05-11 02:47 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +const comparition = maxLessAverage === minLessAverage;
comparison

2021-05-11 02:47 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +const sliceCountries = countries.slice(0, 10)
firstTenCountries

2021-05-12 04:23 UTC, anyruizd commented on Day5/countries.js
> +
❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓ ❓

2021-05-12 04:24 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(numbersList[FIRST]);
Avoid doing calculations inside the console.log. Please assign it to a variable first.

2021-05-12 04:28 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +lastNumber = numbersList[lastNumber];
I don't think `lastNumber` is a good name for the first assignment of the variable since it isn't the last number but its position.

2021-05-12 04:29 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(middleNumber);
I think this would be more readable if you assign the calculation inside `numberList[...]` to a variable.

2021-05-12 04:30 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const middleCompany = itCompanies[Math.floor(itCompanies.length / 2)];
Same as https://github.com/susird/30DaysOfJavaScript/pull/5/files#r630716297

2021-05-12 04:31 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +lastCompany = itCompanies[lastCompany];
Same as in https://github.com/susird/30DaysOfJavaScript/pull/5/files#r630715973

2021-05-12 04:33 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +itCompanies.map(function (x) { return console.log(x.toUpperCase()) });
1. Why do you use an arrow function inside the `forEach` but an anonymous function inside the map?
2. What's x? Do you think is a good name for a variable?

2021-05-12 04:34 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const arraySentence = itCompanies.toString() + ' are big IT companies';
Why aren't you using the interpolation here?

2021-05-12 04:40 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +}
1. This piece of code is not solving the request. You're just checking if Facebook exists, what about if I want to check for other companies? Would I have to write the same piece of code over and over again?
2. Why are you using `const IT_EXIST = 0;`? What's the purpose of that constant? Would the code work if you remove it? Do you know about truth and falsy values?

2021-05-12 04:42 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +});
This is not doing the requested in the exercise. 
1. You're not returning anything
2. you're just printing to the console and anywhere in the exercise asks you to print
3. What does it mean to filter an array? How does the filter method work?

2021-05-12 04:46 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(removeFirtsIt);
The exercise is requesting you to remove the first element of an array. But you are assuming the array will always have Facebook as a first element, then you're finding the index of Facebook which we for sure know is the first element and its index will be obviously 0️⃣.

2021-05-12 04:47 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(removeMiddleIt);
So if I change the order in the array, this piece of code wouldn't work, because you're removing `Apple` instead of the middle element of the array.

2021-05-12 04:47 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(removeLastIt);
Same here.

2021-05-12 04:48 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +lastNumber = numbersList[lastNumber];
I don't think lastNumber is a good name for the first assignment of the variable since it isn't the last number but its position.

2021-05-12 04:49 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(middleNumber);
I think this would be more readable if you assign the calculation inside numberList[...] to a variable.

2021-05-12 04:49 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +itCompanies.map(function (x) { return console.log(x.toUpperCase()) });
1. Why do you use an arrow function inside the forEach but an anonymous function inside the map? Please, be consistent.
2. What's x? Do you think is a good name for a variable?

2021-05-12 05:14 UTC, anyruizd requested changes
😞

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +}
1. This piece of code is not solving the request. You're just checking if Facebook exists, what about if I want to check for other companies? Would I have to write the same piece of code over and over again?
2. Why are you using `const IT_EXIST = 0;`? What's the purpose of that constant? Would the code work if you remove it? Do you know about truthy and falsy values?

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +});
This is not doing the requested in the exercise. 
1. You're not returning anything
2. you're just printing to the console and anywhere in the exercise asks you to print
3. What does it mean to filter an array? How does the filter method work?

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(shoppingCart);
You're missing the CONDITIONAL here.

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +console.log(shoppingCart);
Missing the conditional

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +findCountry(countries, 'Ethiopia');
❤️

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +function findgWebTech(webTech, tech) {
```suggestion
function findWebTech(webTech, tech) {
```

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const minAge = sortAges[FIRST];
`FIRST` is not defined.

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +let maxAge = sortAges.length - 1;
maxAge is not the proper name for this variable since its value is not the max-age but its position in the array

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const halfAge = sortAges.length / 2;
halfAge is not the proper name for this variable

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const secondHalf = sortAges.splice(-halfAge);
firstHalf and secondHalf of what? do you think those are proper variable names?

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +//const ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
Do you?

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +const reduceAgesArray = (accumulator, currentValue) => accumulator + currentValue;
Do you think this is a proper name for this variable? It doesn't mean anything to me, and to you? Maybe you could think about what's the result of that line of code to give it a proper name.

2021-05-12 05:14 UTC, anyruizd commented on Day5/fifthDayExcercises.js
> +}
You're doing the exact same thing for both kinds of arrays: odd and even. And the exercise clearly asks you to add one more country for the first half, if the array is not even. Are you sure is working as intended?

2021-05-14 22:25 UTC, josepplloo requested changes

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +const numberCompanies = itCompanies.length
use `const numberOfCompanies`

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +const calculateMiddlePositionCompany = Math.floor(itCompanies.length / 2)
reserve verbs for function names, in this case, is `middlePositionCompany`

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +});
- forEach does not return anything
- for an iterable use let

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +const sliceFirstPositionCompanies =itCompanies.slice(0, 3)
insert space after equals

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +const sliceLastPositionCompanies = itCompanies.slice(4)
don't guess the length of the array, how dare you.

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +console.log(firstPositionMiddleCompany);
you are not calculating anything so use `middleITCompanyIndex ` instead calculateMiddleItCompany, You are not removing anything from the Array, are you checking your answer?

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +const removeLastPositionIt = itCompanies.slice(-1);
Slice does not remove, you are assing the last position

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +const removeAllIt = itCompanies.splice();
what others ways you have?

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +//3.In the following shopping cart add, remove, edit items
this is hard, I think if you can do this by yourself, you are ready.

2021-05-14 22:25 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +shoppingCart[3] = 'Gren Tea';
👀, you need to look for it and replace

2021-05-25 23:12 UTC, josepplloo requested changes
nice try!

2021-05-25 23:12 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +//it's not finished yet
👀 what is not finish?

2021-05-25 23:12 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +  return array;
`return console.log(array)`?

2021-05-25 23:12 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +  return array;
is this function necessary here?
when did we say try to use functions don't you think this is an overuse of `printArray` function?

2021-05-25 23:12 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +  return arrayOut;
why is this return necessary?

2021-05-25 23:12 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +  const uppercase = arrayInput.map(company => company.toUpperCase());
`return arrayInput.map(company => company.toUpperCase());`

2021-05-25 23:12 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +function companyExistArray(array, company) {
may you rename this function?
![image](https://user-images.githubusercontent.com/1114740/119577159-b465d180-bd7f-11eb-891e-113aa7e679a2.png)

2021-05-25 23:12 UTC, josepplloo commented on Day5/fifthDayExcercises.js
> +console.log(country);
This is incomplete, you did not return the uppercase version of the country, and why are you using `concat` in that way, the exercise says `add`, innit?

2021-05-25 23:12 UTC, josepplloo commented on Day5/level3.js
> +  const sortArray = array.sort((a, b) => a - b);
sortArray is more appropriate for a function, no for the result of a function.
![image](https://user-images.githubusercontent.com/1114740/119578032-60f48300-bd81-11eb-8d7b-d929dbd497af.png)

2021-05-25 23:12 UTC, josepplloo commented on Day5/level3.js
> +}
*cries in array*
![image](https://user-images.githubusercontent.com/1114740/119579194-871b2280-bd83-11eb-8728-49b1a7d831b3.png)

2021-05-25 23:12 UTC, josepplloo commented on Day5/removeExercises.js
> +}
*gurl*
![image](https://user-images.githubusercontent.com/1114740/119579737-abc3ca00-bd84-11eb-9b65-c6ac39f41261.png)

2021-05-25 23:21 UTC, susird commented on Day5/fifthDayExcercises.js
> +//it's not finished yet
It was already done 8eaaf81

2021-05-25 23:48 UTC, susird commented on Day5/fifthDayExcercises.js
> +  return array;
619dd2c

2021-05-26 00:01 UTC, susird commented on Day5/fifthDayExcercises.js
> +  return arrayOut;
7fa3d32

2021-05-26 00:06 UTC, susird commented on Day5/fifthDayExcercises.js
> +  const uppercase = arrayInput.map(company => company.toUpperCase());
1bbc0bb

2021-05-26 19:24 UTC, susird commented on Day5/fifthDayExcercises.js
> +  const uppercase = arrayInput.map(company => company.toUpperCase());
1bbc0bb

2021-05-26 19:40 UTC, susird commented on Day5/fifthDayExcercises.js
> +function companyExistArray(array, company) {
fca7397

2021-05-27 20:11 UTC, susird commented on Day5/fifthDayExcercises.js
> +console.log(country);
ad7679f

2021-05-27 20:17 UTC, susird commented on Day5/level3.js
> +  const sortArray = array.sort((a, b) => a - b);
9a7274b

2021-05-27 20:21 UTC, susird commented on Day5/level3.js
> +}
4b583c0

2021-05-27 22:33 UTC, josepplloo requested changes
keep trying

2021-05-27 22:33 UTC, josepplloo commented on Day5/level3.js
> +}
the word Array in the names is meaningless

2021-05-27 22:33 UTC, josepplloo commented on Day5/level3.js
> +}
we had this conversation before...
https://discordapp.com/channels/827635947214209044/827635947214209050/846839872358449182
![image](https://user-images.githubusercontent.com/1114740/119904888-b4490b80-bf10-11eb-939d-eb2c2fe92fb2.png)

2021-05-27 22:33 UTC, josepplloo commented on Day5/removeExercises.js
> +const itCompanies = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon', 'Holi'];
import this

2021-05-27 22:33 UTC, josepplloo commented on Day5/removeExercises.js
> +const shoppingCart = ['Milk', 'Coffee', 'Tea', 'Honey'];
👀 also, this, if you want...

2021-05-27 22:33 UTC, josepplloo commented on Day5/removeExercises.js
> +}
I was looking for something more ...

```
function removeAllElements() {
  return [];
}
```
this is mine, use your own.

2021-05-28 21:53 UTC, josepplloo approved these changes

2021-05-28 21:53 UTC, josepplloo commented on Day5/removeExercises.js
> +}
👀

2021-06-02 02:13 UTC, anyruizd approved these changes
I'm gonna approve because we've spent enough time on this exercise. But there are still some things that need to be improved.

2021-06-02 19:38 UTC, merged