"Loops" challenge of 30 Days of JavaScript part one
susird/30DaysOfJavaScript pull request #6
Opened 2021-06-02 19:54 UTC by susird

This is the firs "Loops" exercise, level 1 point 1 of 30 days of Javascript :rocket:

2021-06-02 21:02 UTC, josepplloo requested changes

2021-06-02 21:02 UTC, josepplloo commented on Day6/part_one.js
> +iterateWithWhileLoop(0, 10);
👀

2021-06-02 22:19 UTC, anyruizd commented on Day6/part_one.js
> +iterateWithWhileLoop(0, 10);
![image](https://user-images.githubusercontent.com/29681222/120559472-b4d91a80-c3c6-11eb-9399-67bf3e566052.png)

2021-06-02 22:46 UTC, anyruizd approved these changes

2021-06-03 23:40 UTC, josepplloo approved these changes

2021-06-03 23:47 UTC, merged